apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-log-generator
spec:
  selector:
    matchLabels:
      app: random-apache-logger
  replicas: 2
  template:
    metadata:
      labels:
        app: random-apache-logger
    spec:
      containers:
        - name: apache-logger-app
          image: reyiyo/apache-logs-generator
          ports:
            - containerPort: 80
