apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app-deployment
spec:
  selector:
    matchLabels:
      app: static-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
        - name: static-web-app
          image: sagar99/static-html-app
          ports:
            - containerPort: 80