apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  fluentd:
    image:
      repository: localhost:32000/fluentd-local
      tag: v1.14.4-alpine-2
      pullPolicy: IfNotPresent
  fluentbit: {}
  controlNamespace: acquia-system