apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: log-forwarding-output-029119ff-f7d3-447d-b04d-e9208cbc13d3
  namespace: sw12dev
spec:
  syslog:
    host: custom-14.ngc-2.srvs.ahdev.co
    port: 1999
    transport: tls
    insecure: true
    trusted_ca_path:
      mountFrom:
        secretKeyRef:
          name: destination-creds-029119ff-f7d3-447d-b04d-e9208cbc13d3
          key: ca_cert
    buffer:
      flush_interval: 10s